export const REMOVE_TODO_ATTEMPT = "todo/REMOVE_TODO_ATTEMPT";
export const REMOVE_TODO_SUCCESS = "todo/REMOVE_TODO_SUCCESS";
export const REMOVE_TODO_FAILURE = "todo/REMOVE_TODO_FAILURE";

export const COMPLETE_TODO_ATTEMPT = "todo/COMPLETE_TODO_ATTEMPT";
export const COMPLETE_TODO_SUCCESS = "todo/COMPLETE_TODO_SUCCESS";
export const COMPLETE_TODO_FAILURE = "todo/COMPLETE_TODO_FAILURE";

export default {};